---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ruedigermueller
  labels:
    app: vocab
    tier: frontend
data:
  # content below comes from .nginx/nginx_docker.conf
  # port has to be exeplicitely set to 8080
  config: >
    worker_processes 4;
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      server {
        listen 8080;

        root /usr/share/nginx/html;
        index index.html;

        location /backend {
          proxy_pass http://vocab-backend:3000;
        }

        location / {  
          try_files $uri$args $uri$args/ /index.html;
        }
      }
    }