---
apiVersion: v1
kind: Service
metadata:
  name: vocab-frontend
  labels:
    app: vocab
    tier: frontend
spec:
  selector:
    app: vocab
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort