---
apiVersion: v1
kind: Service
metadata:
  name: vocab-frontend
spec:
  selector:
    app: vocab
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-frontend
spec:
  selector:
    matchLabels:
      app: vocab
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: vocab
        tier: frontend
    spec:
      containers:
      - name: vocab
        image: "ruedigermueller/vocab_frontend"
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: nginx.conf