---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  labels:
    app: vocab
    tier: frontend
data:
  config: >
    worker_processes 4;
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      server {
        listen 8080;
        location / {
          root  /usr/share/nginx/html/frontend;
          index index.html;
          try_files $uri$args $uri$args/ /index.html;
        }
        location /backend {
          proxy_pass http://vocab-backend:3000;
        }
      }
    }