---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  labels:
    app: vocab
    tier: frontend
data:
  config: >
    worker_processes 4;
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;
        location / {
          root  /usr/share/nginx/html/frontend;
          index index.html;
          try_files $uri$args $uri$args/ /index.html;
        }
        location /backend {
          proxy_pass http://vocab-backend:3000;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: vocab-frontend
  labels:
    app: vocab
    tier: frontend
spec:
  selector:
    app: vocab
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocab-frontend
  labels:
    app: vocab
    tier: frontend
spec:
  selector:
    matchLabels:
      app: vocab
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: vocab
        tier: frontend
    spec:
      containers:
      - name: vocab
        image: "ruedigermueller/vocab_frontend"
        volumeMounts:
        - name: nginx-config		
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf	
      volumes:		
      - name: nginx-config		
        configMap:		
          name: nginx-config		
          items:		
          - key: config		
            path: nginx.conf
