version: 2.1

jobs:
  build:
    working_directory: ~/vocab_frontend
    docker:
      - image: circleci/node:14.15-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install
          command: npm install
      - save_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: 
          name: Run tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: test-results

  docker_build:
    working_directory: ~/vocab_frontend
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t ruedigermueller/vocab_frontend .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ruedigermueller/vocab_frontend
  
  heroku_deploy:
    working_directory: ~/vocab_frontend
    docker:
      - image: circleci/node:14.15
    steps:
      # - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Deploy image to Heroku
          command: |
            echo $HEROKU_API_KEY | docker login -u=_ --password-stdin registry.heroku.com
            docker pull ruedigermueller/vocab_frontend
            docker tag ruedigermueller/vocab_frontend registry.heroku.com/$HEROKU_DOCKER_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_DOCKER_APP_NAME/web

# heroku container:release web --app $HEROKU_DOCKER_APP_NAME

workflows:
  deploy:
    jobs:
      - build
      - docker_build:
          requires:
             - build
          context: vocab
      - heroku_deploy:
          requires:
             - docker_build
          context: vocab