version: 2.1

jobs:
  install_and_test:
    docker:
      - image: circleci/node:14.15-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - store_test_results:
          path: test-results

  docker_build:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t ruedigermueller/vocab_frontend .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ruedigermueller/vocab_frontend

  heroku_deploy:
    docker:
      - image: circleci/node:14.15
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Deploy image to Heroku
          command: |
            echo $HEROKU_API_KEY | docker login -u=_ --password-stdin registry.heroku.com
            docker pull ruedigermueller/vocab_frontend
            docker tag ruedigermueller/vocab_frontend registry.heroku.com/$HEROKU_PROD/web
            docker push registry.heroku.com/$HEROKU_PROD/web

  heroku_release:
    docker:
      - image: circleci/node:14.15
    steps:
      - run:
          name: Install Heroku CLI (If not installed)
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Release on Heroku
          command: heroku container:release web --app $HEROKU_PROD

workflows:
  deploy:
    jobs:
      - install_and_test
      - docker_build:
          requires:
            - install_and_test
          context: vocab
      - heroku_deploy:
          requires:
            - docker_build
          context: vocab
      # - hold:
      #     type: approval
      #     requires:
      #       - heroku_deploy
      - heroku_release:
          requires:
            - heroku_deploy
