version: 2.1

orbs:
   heroku: circleci/heroku@1.0.1 

jobs:
  build:
    working_directory: ~/vocab_frontend
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: vocab_frontend-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      #- run: npm run test-heroku -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build-heroku
      - store_test_results:
          path: test-results
      #- run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch