name: Build and deploy for manual test

on:
  workflow_dispatch

jobs: 
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        env:
          CHROME_BIN: "/usr/bin/google-chrome"
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          # Note: tags has to be all lower-case
          tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/vocab_frontend:undertest
          # build on feature branches, push only on main branch
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/vocab_frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/vocab_frontend:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.build_docker_image.outputs.digest }}
  
  deploy_to_heroku_for_manual_test:
    needs: [build_docker_image]
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub, deploy & release on Heroku test space
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login -u=_ --password-stdin registry.heroku.com
          docker pull ruedigermueller/vocab_frontend:undertest
          docker tag ruedigermueller/vocab_frontend:undertest registry.heroku.com/vocabfetest/web
          docker push registry.heroku.com/vocabfetest/web
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web --app vocabfetest