name: Build and test project

on:
  push:
    branches-ignore:
      - master

jobs:
  build_and_test:
    uses: RuedigerMueller/GitHubWorkflows/.github/workflows/build_and_push.yml@main
    with:
      DOCKERHUB_USERNAME: ruedigermueller
      DOCKERHUB_REPOSITORY: vocab_frontend
      DOCKERHUB_PUSH: false
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}    
