name: Promote tested build to production

on:
  workflow_dispatch

jobs:
  promoto_to_prod:
    uses: RuedigerMueller/GitHubWorkflows/.github/workflows/promote2prod.yml@main
    with:
      DOCKERHUB_USERNAME: ruedigermueller
      DOCKERHUB_REPOSITORY: vocab_frontend
      HEROKU_REPOSITORY: vocabfetest
      SCP_APP_NAME: vocab_frontend
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      SCP_USER: ${{ secrets.SCP_USER }}
      SCP_PASSWORD: ${{ secrets.SCP_PASSWORD }}
      SCP_ORG: ${{ secrets.SCP_ORG }}
      SCP_SPACE: ${{ secrets.SCP_SPACE }}
      # JWT_SECRET: ${{ secrets.JWT_SECRET }}